### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by korkeep** [korkeep/MoaMoa#13]
@korkeep @JustKode @SeongHyukJang @syoon0624

### Github
- [x] 최종 작업 Merge
- [x] Frontend README.md
- [x] Backend README.md
### Project
- [x] PPT 작성
- [x] Frontend 보고서 작성
- [x] Backend 보고서 작성
- [x] 발표 영상 제작
- [x] 데모 영상 제작
- [x] 조별 평가표 작성

**Comment by korkeep** [comment]
고생하셨습니다 여러분 :)
